# Generated by Django 5.0 on 2024-01-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(default=None, max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('petname', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=None)),
                ('description', models.TextField(default=None)),
            ],
        ),
    ]
