# Generated by Django 5.0 on 2024-01-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='pets',
            name='pimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
